# Generated by Django 5.0.6 on 2024-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_alter_flight_airplane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
