# Generated by Django 5.0.6 on 2024-06-06 13:54

import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_alter_airplanetype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["distance"]},
        ),
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=flight.models.airplane_image_path
            ),
        ),
    ]
