# Generated by Django 5.0.6 on 2024-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0005_alter_route_options_airplane_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="flights", to="flight.crew"
            ),
        ),
    ]
