# Generated by Django 5.0.6 on 2024-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0006_flight_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flights", to="flight.crew"),
        ),
    ]
